language: python
python:
  - 3.8
services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to dockerhub

script:
  - docker build -t joffreybvn/alan-turing-bot:latest .

deploy:
  provider: script
  script:
    docker push joffreybvn/flask-demo-api:latest;
  on:
    branch: master